version: '3.7'
services:
   elide-backend-dev:
      container_name: elide-backend-dev
      build:
         context: .
         dockerfile: Dockerfile
      ports:
         - 5000:5000
         - 5555:5555
      depends_on:
         - postgres
         - redis
         - mongo
      env_file:
         - .env
      environment:
         - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
         - BULL_REDIS_HOST=redis
         - BULL_REDIS_PORT=6379
      volumes:
         - ./src:/app/src
         - eldie_nodemodules:/app/node_modules

   postgres:
      image: postgres:14-alpine
      container_name: elide-postgres
      restart: always
      ports:
         - 5432:5432
      environment:
         - POSTGRES_USER=${POSTGRES_USER}
         - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
         - POSTGRES_DB=${POSTGRES_DB}
      volumes:
         - elide_postgres:/var/lib/postgresql/data

   redis:
      image: redis:7.0-alpine
      container_name: elide-redis
      restart: always
      ports:
         - 6379:6379

   mongo:
      image: mongo
      container_name: elide-mongo
      restart: always
      ports:
         - 27017:27017
      environment:
         - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
         - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      volumes:
         - elide_mongo:/data/db

volumes:
   elide_postgres:
      driver: local
   eldie_nodemodules:
      driver: local
   elide_mongo:
      driver: local
